
export enum View {
  DASHBOARD = 'DASHBOARD',
  ADVISOR = 'ADVISOR',
  WEEKLY_TIPS = 'WEEKLY_TIPS',
  BEST_PRACTICES = 'BEST_PRACTICES',
  TRAINING = 'TRAINING',
  REPORT_ANALYZER = 'REPORT_ANALYZER',
  TOOLKIT = 'TOOLKIT',
  SOCIAL_TRENDS = 'SOCIAL_TRENDS'
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
  isError?: boolean;
  sources?: Array<{ title: string; url: string }>;
  isPinned?: boolean;
}

export interface IntelligenceBriefing {
  id: string;
  timestamp: number;
  content: string;
  sources: Array<{ title: string; url: string }>;
}

export interface SocialMediaNotification {
  title: string;
  summary: string;
  category: string;
  priority: 'normal' | 'high';
  source: string;
  timestamp: string;
}

export interface SocialMediaIntel {
  notifications: SocialMediaNotification[];
  hourly_digest: {
    top_story: string;
    key_updates: string[];
    emerging_trends: string[];
    generated_at: string;
  };
}

export interface BestPracticeItem {
  title: string;
  summary: string;
  source: string;
  date: string;
}

export interface TrainingModule {
  targetAudience: string;
  topic: string;
  content: string;
  generatedDate: string;
}

export interface StoredTrainingModule extends TrainingModule {
  id: string;
  timestamp: number;
}

export interface Template {
  id: string;
  title: string;
  description: string;
  content: string;
}

export interface StoredReport {
  id: string;
  timestamp: number;
  dateStr: string;
  content: string;
  analysis: string;
}

export interface WeeklyTip {
  id: string;
  weekDate: string;
  topic: string;
  content: string;
  isAutoGenerated: boolean;
  timestamp: number;
}

export interface UserProfile {
  name: string;
  phoneNumber: string; // International format for WhatsApp
  email: string;
}

export interface KnowledgeDocument {
  id: string;
  title: string;
  content: string;
  dateAdded: string;
}

export interface SavedTrend {
  id: string;
  topic: string;
  timestamp: number;
}

export enum SecurityRole {
  GUARD = 'Security Guard',
  SUPERVISOR = 'Site Supervisor',
  GEN_SUPERVISOR = 'General Supervisor'
}
